name: Hades Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
    steps:
    - uses: actions/checkout@master
    - run: bash deploy.sh
